export const ROUTES = {
  HOME: '/',
  SOLAR: {
    ROOT: '/solar',
    SYSTEMS: '/solar/systems',
    INSTALLATION: '/solar/installation',
    UPGRADES: '/solar/upgrades',
  },
  BATTERIES: {
    ROOT: '/batteries',
    SOLAR_BATTERIES: '/batteries/solar-batteries',
    SOLAR_PLUS_BATTERY: '/batteries/solar-plus-battery',
    BATTERY_BACKUP: '/batteries/battery-backup',
  },
  EV_CHARGER: '/ev-charger',
  EXISTING_SOLAR: {
    ROOT: '/existing-solar',
    HEALTH_CHECK: '/existing-solar/health-check',
    SAVINGS: '/existing-solar/savings',
    UPGRADE: '/existing-solar/upgrade',
    ADD_BATTERY: '/existing-solar/add-battery',
  },
  CALCULATORS: {
    ROOT: '/calculators',
    SOLAR_SAVINGS: '/calculators/solar-savings',
    SYSTEM_SIZE: '/calculators/system-size',
    PAYBACK: '/calculators/payback',
    BATTERY_SAVINGS: '/calculators/battery-savings',
    BATTERY_SIZE: '/calculators/battery-size',
    QUOTE_COMPARISON: '/calculators/quote-comparison',
    SAVINGS_SO_FAR: '/calculators/savings-so-far',
    IS_SOLAR_RIGHT: '/calculators/is-solar-right-for-me',
  },
  LEARN: {
    ROOT: '/learn',
    KNOWLEDGE_HUB: '/learn/knowledge-hub',
    BLOG: '/learn/blog',
  },
  PROJECTS: '/projects',
  REVIEWS: '/reviews',
  ABOUT: {
    ROOT: '/about',
    TRENT: '/about/trent',
  },
  SERVICE_AREAS: '/service-areas',
  RESOURCES: {
    ROOT: '/resources',
    BUYING_CHECKLIST: '/resources/buying-checklist',
    BUYER_GUIDE: '/resources/buyer-guide',
    BATTERY_DECISION_GUIDE: '/resources/battery-decision-guide',
    QUOTE_REVIEW: '/resources/quote-review',
    BILL_REVIEW: '/resources/electricity-bill-review',
  },
  FAQ: '/faq',
  FREE_ASSESSMENT: '/get-started/free-assessment',
  CONTACT: '/contact',
  LEGAL: {
    PRIVACY: '/legal/privacy-policy',
    TERMS: '/legal/terms-conditions',
    TERMS_OF_TRADE: '/legal/terms-of-trade',
  },
} as const;
